version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: lifecraft-postgres
    environment:
      POSTGRES_USER: lifecraft
      POSTGRES_PASSWORD: lifecraft_dev_2025
      POSTGRES_DB: lifecraft_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U lifecraft -d lifecraft_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Optional: Adminer for database management UI
  adminer:
    image: adminer:latest
    container_name: lifecraft-adminer
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local