# Render Blueprint for LifeCraft Bot
# This file defines the infrastructure for deploying on Render

databases:
  - name: lifecraft-db
    databaseName: lifecraft_prod
    user: lifecraft_user
    plan: starter # Change to 'standard' for production
    
services:
  # Main Web Service
  - type: web
    name: lifecraft-bot
    runtime: node
    plan: starter # Change to 'standard' for production
    rootDir: lifecraft-bot
    buildCommand: npm ci && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: lifecraft-db
          property: connectionString
      - key: SESSION_SECRET
        generateValue: true
      - key: ANTHROPIC_API_KEY
        sync: false # Set in Render dashboard
      - key: OPENAI_API_KEY
        sync: false # Set in Render dashboard
      - key: PORT
        value: 3000
    healthCheckPath: /api/health
    autoDeploy: true # Automatically deploy on push to main branch

  # Background Worker (Optional - for async tasks)
  # - type: worker
  #   name: lifecraft-worker
  #   runtime: node
  #   buildCommand: npm ci && npm run build:render
  #   startCommand: npm run worker
  #   envVars:
  #     - key: NODE_ENV
  #       value: production
  #     - key: DATABASE_URL
  #       fromDatabase:
  #         name: lifecraft-db
  #         property: connectionString

# Cron Jobs (Optional - for scheduled tasks)
# - type: cron
#   name: lifecraft-cleanup
#   runtime: node
#   schedule: "0 2 * * *" # Daily at 2 AM
#   buildCommand: npm ci
#   startCommand: npm run cleanup
#   envVars:
#     - key: DATABASE_URL
#       fromDatabase:
#         name: lifecraft-db
#         property: connectionString