version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: wfed119-db
    environment:
      POSTGRES_DB: wfed119
      POSTGRES_USER: ${DB_USER:-admin}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-wfed119_dev_password}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-admin} -d wfed119"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - wfed119-network

  qdrant:
    image: qdrant/qdrant:latest
    container_name: wfed119-qdrant
    ports:
      - "6333:6333"
      - "6334:6334"  # Web UI
    volumes:
      - qdrant-data:/qdrant/storage
    environment:
      QDRANT__SERVICE__HTTP_PORT: 6333
      QDRANT__SERVICE__GRPC_PORT: 6334
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - wfed119-network

  redis:
    image: redis:7-alpine
    container_name: wfed119-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - wfed119-network

  # Optional: pgAdmin for database management
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: wfed119-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-admin@wfed119.dev}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-admin}
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8080:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - wfed119-network
    profiles:
      - admin  # Use with: docker-compose --profile admin up

volumes:
  postgres-data:
    driver: local
  qdrant-data:
    driver: local
  redis-data:
    driver: local
  pgadmin-data:
    driver: local

networks:
  wfed119-network:
    driver: bridge