# Render Blueprint for LifeCraft Bot
# This file defines the infrastructure for deploying on Render
# Using Supabase for database (no PostgreSQL database needed)

services:
  # Main Web Service
  - type: web
    name: lifecraft-bot
    runtime: node
    plan: starter # Change to 'standard' for production
    rootDir: .
    buildCommand: npm ci && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_SUPABASE_URL
        sync: false # Set in Render dashboard - Required
      - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
        sync: false # Set in Render dashboard - Required
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false # Set in Render dashboard - Required
      - key: ANTHROPIC_API_KEY
        sync: false # Set in Render dashboard - Optional
      - key: OPENAI_API_KEY
        sync: false # Set in Render dashboard - Optional
      # Do not set PORT; Render provides it automatically
    healthCheckPath: /api/health
    autoDeploy: true # Automatically deploy on push to main branch

  # Background Worker (Optional - for async tasks)
  # - type: worker
  #   name: lifecraft-worker
  #   runtime: node
  #   buildCommand: npm ci && npm run build:render
  #   startCommand: npm run worker
  #   envVars:
  #     - key: NODE_ENV
  #       value: production
  #     - key: DATABASE_URL
  #       fromDatabase:
  #         name: lifecraft-db
  #         property: connectionString

# Cron Jobs (Optional - for scheduled tasks)
# - type: cron
#   name: lifecraft-cleanup
#   runtime: node
#   schedule: "0 2 * * *" # Daily at 2 AM
#   buildCommand: npm ci
#   startCommand: npm run cleanup
#   envVars:
#     - key: DATABASE_URL
#       fromDatabase:
#         name: lifecraft-db
#         property: connectionString
